import mongoose from 'mongoose';
import { collectionNames } from './utils.js';

const { Schema } = mongoose;

export const model = collectionNames.malshab;
export const schema = new Schema(
  {
    identityNumber: {
      type: String,
      required: true,
      unique: true,
    },
    personalNumber: String,
    firstName: String,
    lastName: String,
    email: String,
    gender: Number,
    birthDate: Date,
    medicalProfile: Number,
    kaba: Number,
    dapar: Number,
    continuousDapar: Number,
    zadak: Number,
    kahas: Number,
    major: Number,
    aptitudeTest: {
      svivatHadraha: Number,
      svivatSade: Number,
      svivatTipulBeadam: Number,
      svivatTechniAhzaka: Number,
      svivatTechniHafala: Number,
      svivatMinhalVerigun: Number,
      svivatIbudMeida: Number,
      madadKeshevMitmasheh: Number,
      madadKeshevSelektivi: Number,
      madadPikud: Number,
      madadAvodatTsevet: Number,
      madadHashkaVehatmada: Number,
      madadBashlutVebagrut: Number,
      madadHitnahagutMisgartit: Number,
    },
    attachments: [String],
    statusId: Number,
    statusName: String,
    addresses: [
      {
        street: String,
        houseNumber: Number,
        cityId: Number,
        cityName: String,
      },
    ],
    homePhoneNumber: String,
    personalPhoneNumber: String,
    birthCountry: String,
    imigrationDate: Date,
    hasIsraeliCitizenship: Boolean,
    hasAnotherCitizenship: Boolean,
    isOnlyChild: Boolean,
    isBereaved: Boolean,
    schoolId: Number,
    schoolName: String,
    majorName: String,
    languages: [
      {
        languageId: Number,
        languageName: String,
        languageLevel: Number,
        languageLevelDesc: String,
      },
    ],
    englishGrade: Number,
    tzalagAgrade: Number,
    tzalagBgrade: Number,
    isPassedKogTirgum: Boolean,
    isPersonalSurvey: Boolean,
    isReligiousSchool: Boolean,
    shakimSchoolAverage: Number,
    isArabist: Boolean,
    pdfQuestionnaire: String,
    grades: [
      {
        examId: Number,
        examName: String,
        grade: Number,
      },
    ],
  },
  {
    timestamps: true,
    toObject: {
      virtuals: true,
    },
    toJSON: {
      virtuals: true,
    },
  },
);

// Data
export default [
  {
    identityNumber: '222222222',
    personalNumber: '0',
    personalPhoneNumber: '05000000000000',
    firstName: 'נועה',
    lastName: 'קירל',
    gender: 2,
    birthDate: '2003-05-09T00:00:07.996+00:00',
    medicalProfile: 82,
    kaba: 56,
    dapar: 90,
    addresses: [
      {
        cityId: 1,
        cityName: 'ראשון לציון',
        houseNumber: 12,
        street: 'הרצל',
      },
    ],
    birthCountry: 'רוסיה',
    imigrationDate: '2005-05-13T00:00:07.996+00:00',
    hasIsraeliCitizenship: true,
    hasAnotherCitizenship: false,
    isBereaved: false,
    schoolName: 'בן גוריון',
    email: 'noa@gmail.com',
    attachments: [],
  },
  {
    identityNumber: '333333333',
    personalPhoneNumber: '05000000000000',
    personalNumber: '0',
    firstName: 'חיים',
    lastName: 'כהן',
    gender: 2,
    birthDate: '2003-05-09T00:00:07.996+00:00',
    medicalProfile: 82,
    kaba: 56,
    dapar: 90,
    addresses: [
      {
        cityId: 1,
        cityName: 'ראשון לציון',
        houseNumber: 12,
        street: 'הרצל',
      },
    ],
    birthCountry: 'רוסיה',
    imigrationDate: '2005-05-13T00:00:07.996+00:00',
    hasIsraeliCitizenship: true,
    hasAnotherCitizenship: false,
    isBereaved: false,
    schoolName: 'בן גוריון',
    email: 'adi@gmail.com',
    attachments: [],
  },
  {
    identityNumber: '555555555',
    personalPhoneNumber: '05000000000000',
    personalNumber: '0',
    firstName: 'ישראל',
    lastName: 'ישראלי',
    gender: 1,
    birthDate: '2003-05-09T00:00:07.996+00:00',
    medicalProfile: 82,
    kaba: 56,
    dapar: 90,
    addresses: [
      {
        cityId: 1,
        cityName: 'ראשון לציון',
        houseNumber: 12,
        street: 'הרצל',
      },
    ],
    birthCountry: 'רוסיה',
    imigrationDate: '2005-05-13T00:00:07.996+00:00',
    hasIsraeliCitizenship: true,
    hasAnotherCitizenship: false,
    isBereaved: false,
    schoolName: 'בן גוריון',
    email: 'israel@gmail.com',
    attachments: [],
  },
  {
    identityNumber: '999999999',
    personalPhoneNumber: '05000000000000',
    personalNumber: '0',
    firstName: 'דנה',
    lastName: 'זרמון',
    gender: 2,
    birthDate: '2003-05-09T00:00:07.996+00:00',
    medicalProfile: 82,
    kaba: 56,
    dapar: 90,
    addresses: [
      {
        cityId: 1,
        cityName: 'ראשון לציון',
        houseNumber: 12,
        street: 'הרצל',
      },
    ],
    birthCountry: 'רוסיה',
    imigrationDate: '2005-05-13T00:00:07.996+00:00',
    hasIsraeliCitizenship: true,
    hasAnotherCitizenship: false,
    isBereaved: false,
    schoolName: 'בן גוריון',
    email: 'dana@gmail.com',
    attachments: [],
  },
];
